"""Override just the model on an arm, for a one-variable comparison.

The model is the most expensive change available here, so it has to be the
only one: everything else in a run has to match the arm it is compared
against, or the difference in the result cannot be attributed. This reads a
tracked arm, changes `llm.model`, and writes a gitignored local config with
the real endpoint already in it.

It refuses if the result would differ from the arm in more than the model
and the endpoint, because a config that drifted would still look like a
model comparison in the results table.

Usage:
  python tools/make_model_arm.py ptr_mem hauhau-qwen-27b
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs" / "traitors"
DONOR = CONFIGS / "season_uk_s01.fix_en.local.yaml"

NOTE = """\
# GENERATED by tools/make_model_arm.py - do not edit by hand.
#
# Arm: {arm}, model: {model}
#
# Identical to season_uk_s01.{arm}.yaml except `llm.model` and `base_url`.
# Gitignored: it carries a real network address.
"""


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    arm, model = sys.argv[1], sys.argv[2]

    source = CONFIGS / f"season_uk_s01.{arm}.yaml"
    if not source.exists():
        raise SystemExit(f"no such arm: {source.name}")
    text = source.read_text()

    endpoint = re.search(r"^  base_url: (\S+)", DONOR.read_text(),
                         re.MULTILINE)
    if not endpoint:
        raise SystemExit(f"no base_url in {DONOR.name}")

    def swap(pattern: str, value: str, label: str) -> str:
        new, n = re.subn(pattern, value, text, count=1, flags=re.MULTILINE)
        if n != 1:
            raise SystemExit(
                f"could not set {label}; the anchor line is missing, and a "
                f"config that silently keeps the old value would be reported "
                f"as a model comparison"
            )
        return new

    before = text
    text = swap(r"^  model: .*$", f"  model: {model}", "llm.model")
    text = swap(r"^  base_url: .*$", f"  base_url: {endpoint.group(1)}",
                "llm.base_url")

    changed = sum(
        1 for a, b in zip(before.splitlines(), text.splitlines()) if a != b
    ) + abs(len(before.splitlines()) - len(text.splitlines()))
    if changed > 2:
        raise SystemExit(f"would change {changed} lines, expected 2")

    out = CONFIGS / f"season_uk_s01.{arm}-{model}.local.yaml"
    out.write_text(NOTE.format(arm=arm, model=model) + text)
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"arm:    season_uk_s01.{arm}.yaml")
    print(f"model:  {model}")
    print(f"differs in {changed} lines (model and base_url only)")


if __name__ == "__main__":
    main()