"""Give an arm its machine-specific config, without touching the tracked one.

A run needs a real `base_url`; the tracked arm carries the `HOST_A`
placeholder and `*.local.yaml` is gitignored for exactly that reason. The
local file is produced by copying the arm and substituting the endpoint from
an existing local config, so the address lives in one place and a future
host change does not have to be hunted down in several files.

The copy is verified rather than assumed: if the arm and the local file ever
differ by more than that one line, the run is no longer the arm it claims to
be, and that is worth failing on.

Usage:
  python tools/make_local_arm.py ptr_mem
"""
from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs" / "traitors"
# The local config whose endpoint is copied. Any local config will do; this is
# the one the previous runs used.
DONOR = CONFIGS / "season_uk_s01.fix_en.local.yaml"


def base_url_of(path: Path) -> str:
    match = re.search(r"^  base_url: (\S+)", path.read_text(), re.MULTILINE)
    if not match:
        raise SystemExit(f"no base_url in {path.name}")
    return match.group(1)


def main() -> None:
    name = sys.argv[1] if len(sys.argv) > 1 else "ptr_mem"
    arm = CONFIGS / f"season_uk_s01.{name}.yaml"
    if not arm.exists():
        raise SystemExit(f"no such arm: {arm.name}")

    url = base_url_of(DONOR)
    text = re.sub(r"^  base_url: \S+", f"  base_url: {url}", arm.read_text(),
                  count=1, flags=re.MULTILINE)

    out = CONFIGS / f"season_uk_s01.{name}.local.yaml"
    out.write_text(
        "# GENERATED by tools/make_local_arm.py from the tracked arm plus the\n"
        "# endpoint used by the previous runs. Gitignored: it holds a real\n"
        "# network address, which must not enter this repository.\n" + text
    )

    added = [
        line for line in difflib.unified_diff(
            arm.read_text().splitlines(), text.splitlines(), lineterm="", n=0,
        )
        if (line.startswith("+") or line.startswith("-"))
        and not line.startswith(("+++", "---"))
    ]
    print(f"wrote {out.relative_to(ROOT)}")
    print(f"endpoint: {url}")
    print(f"differs from the tracked arm in {len(added)} lines (base_url only)")


if __name__ == "__main__":
    main()