"""Generate the four pointer arms from one base config.

Each arm is the base with three flags set, so the arms cannot drift apart in
any way the diff does not show. They are generated rather than hand-written
because four near-identical YAML files would eventually differ in something
nobody intended - and an A/B whose arms differ by an accidental byte is
worse than no A/B, because the result still looks like a result.

The arms:

  base      no pointers at all. The reference for both strategies.
  opt       pointer requested, not required.
  req       pointer requested and required by the schema.
  ptr       `req` plus pointer memory, so every message leaves a decaying
            one-line trace and the transcript has something to shrink into.

Run one:
  python tools/make_pointer_arms.py
  uv run --no-sync python -m simulation run \\
      configs/traitors/season_uk_s01.ptr_opt.local.yaml --game-id uk-s01-ptr-opt
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASE = ROOT / "configs" / "traitors" / "season_uk_s01.fix_en.yaml"
OUT = ROOT / "configs" / "traitors"

HEADER = """\
# GENERATED by tools/make_pointer_arms.py - do not edit by hand.
#
# Arm: {name}
{blurb}
#
# Everything except the three flags below is identical to
# season_uk_s01.fix_en.yaml, which is the `base` arm's reference.
"""

# Every blurb line carries its own `#`. A bare line at the top of a YAML
# document is not a comment, it starts a second document, and the config
# then fails to load - so the prefix belongs to the text, not to a
# substitution done afterwards.
BLURBS = {
        "ptr_opt": (
            "# Pointer requested, not required.\n"
            "#   A reply without one is accepted and memory falls back to its\n"
            "#   deterministic clause. This is the arm that can look successful\n"
            "#   whether or not the model ever writes a pointer, which is why the\n"
            "#   co-generation rate has to be read rather than assumed."
        ),
        "ptr_req": (
            "# Pointer requested and required by the response schema.\n"
            "#   A reply without one is refused and retried, so this arm measures\n"
            "#   what the model does when held to it - including the retry cost\n"
            "#   when it refuses."
        ),
        "ptr_mem": (
            "# Pointer required, plus a decaying pointer memory for every\n"
            "#   message. This is the arm that can actually shrink the prompt:\n"
            "#   the transcript is 93% of it, and without a short trace to\n"
            "#   replace, there is nothing for a smaller window to fall back on."
        ),
    }


FLAGS = {
    "ptr_opt": {"co_generate_gist": True, "gist_required": False,
                "pointer_memory": False},
    "ptr_req": {"co_generate_gist": True, "gist_required": True,
                "pointer_memory": False},
    "ptr_mem": {"co_generate_gist": True, "gist_required": True,
                "pointer_memory": True},
}


def render(flags: dict[str, object]) -> str:
    """The base config with the arm's flags written into the `game:` block."""
    text = BASE.read_text()
    block = "\n".join(f"  {k}: {str(v).lower()}" for k, v in flags.items())
    # Anchored to a flag the base already sets, so this lands in `game:` and
    # not in whichever other block also happens to mention a boolean.
    text, n = re.subn(
        r"(  anti_echo_instructions: true\n)",
        r"\1" + block + "\n",
        text,
        count=1,
    )
    if n != 1:
        raise SystemExit(
            "could not find the anchor flag in the base config; "
            "the generator needs updating before it can be trusted"
        )
    return text


def main() -> None:
    names = sys.argv[1:] or list(BLURBS)
    for name in names:
        if name not in BLURBS:
            raise SystemExit(f"unknown arm '{name}'; known: {sorted(BLURBS)}")
        blurb = BLURBS[name]
        header = HEADER.format(name=name, blurb=blurb)
        out = OUT / f"season_uk_s01.{name}.yaml"
        out.write_text(header + render(FLAGS[name]))
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()