"""Generate the random-deal variants of the season arms.

Every season arm pins `game.traitor_names` to the three original traitors,
because each one is a season replay: wilf, amanda and alyssa draw first in
all of them. That is right for a replay and wrong for an arm comparison -
the deal becomes a constant nobody varies, so a behaviour shared by all
seven arms may be a property of those three personas rather than of the
flags under test.

These arms are those same configs with the pin dropped, so the engine draws
the traitors from the seed instead (engine/game_engine.py: `rng.sample`).
The draw is a function of the seed and the cast and nothing else, so the
whole set shares one deal - same trio, same item awards, same ambitions -
and the only thing that differs across a sweep is the flag each arm turns
on.

Three lines differ from the tracked arm: `traitor_names` is gone, `seed`
selects the deal, and `max_concurrency` is lowered so the arms can run at
the same time (see below). No model is consulted to build them.

Run:
  uv run --no-sync python tools/make_rand_arms.py           # the default set
  uv run --no-sync python tools/make_rand_arms.py ledger    # named arms

The output is verified rather than assumed: each generated file is re-parsed
and checked, so a substitution that lands in the wrong block fails here
instead of running quietly as an arm nobody asked for.
"""
from __future__ import annotations

import random
import re
import sys
from itertools import count
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs" / "traitors"

# The arms that form the comparison. The historical ones (run, r2, r2c4, r3)
# and the language pair (fix_hl, hinglish) are left out: the first are older
# baselines that differ in several flags at once, the second vary language
# rather than a mechanic, so sweeping them together would confound the arm
# differences this set exists to isolate.
ARMS = ("fix_en", "noecho", "ptr_opt", "ptr_req", "ptr_mem", "ledger",
        "ledger_room")

# One request in flight per arm rather than the tracked four: the sweep runs
# every arm at once against a single host, and the arms themselves record 8
# in flight as clean and 16 as degraded, because past what a host serves in
# parallel the extra requests only queue into the timeout. Seven arms at four
# apiece would be 28.
SWEEP_CONCURRENCY = 1

# Anchored on the comment the arms carry above the value, so the replacement
# cannot land on some other `max_concurrency` line. The match count is
# asserted: a generator that silently stops matching is worse than none.
CONCURRENCY_BLOCK = re.compile(
    r"  # 4 in flight,.*?  max_concurrency: \d+\n", re.DOTALL
)
PIN_LINE = re.compile(r"^  traitor_names: \[[^\]]*\]\n", re.MULTILINE)
SEED_LINE = re.compile(r"^seed: \d+\n", re.MULTILINE)

HEADER = """\
# GENERATED by tools/make_rand_arms.py from {source} - do not edit by hand.
#
# Random-deal variant of {arm}: the tracked arm with its `traitor_names` pin
# removed, so the engine draws the traitors from the seed instead of replaying
# the season's. One deal across the whole sweep, because the draw depends on
# the seed and the cast and nothing else.
#
{rule}
#
# max_concurrency is {conc} in flight per arm rather than {arm_conc}, so all
# {n} arms can run at once on one host; {n} arms at {arm_conc} apiece would be
# {naive} in flight. Neither number is a measured host limit: those levels came
# through a client that announced `Connection: close` on every request, which
# the server dropped most of the time (see the header of fix_hl).
#
# The rest of the file is the tracked arm byte for byte.
"""


def pick_deal(player_names: list[str], traitors: int,
              exclude: list[str]) -> tuple[int, list[str]]:
    """The lowest seed whose draw keeps none of the season's traitors.

    Lowest rather than chosen to taste: a seed picked for a pretty deal is a
    choice nobody can reproduce from the config, while "the first one that
    qualifies" is a rule anyone can re-derive. Holdout seeds (`seed % 10 >= 7`
    in the run ledger) are skipped, because a holdout run may not drive a
    promotion decision and informing one is the point of the sweep.
    """
    for seed in count(0):
        if seed % 10 >= 7:
            continue
        draw = random.Random(seed).sample(player_names, traitors)
        if not set(draw) & set(exclude):
            return seed, sorted(draw)
    raise AssertionError("unreachable")


def render(text: str, seed: int, arm_conc: int) -> str:
    """The source arm with the pin dropped, the seed set and concurrency cut."""
    text, n_pin = PIN_LINE.subn("", text, count=1)
    text, n_conc = CONCURRENCY_BLOCK.subn(
        f"  # {SWEEP_CONCURRENCY} in flight: the random-deal arms are meant to\n"
        f"  # run together on one host, so each gives up its share of the host\n"
        f"  # rather than every arm's calls landing at once. An in-flight level,\n"
        f"  # not a measured host limit - see the header of fix_hl for why the\n"
        f"  # earlier host numbers cannot be read as one.\n"
        f"  # If this run stalls: --resume --idle-seconds 5\n"
        f"  max_concurrency: {SWEEP_CONCURRENCY}\n",
        text, count=1,
    )
    text, n_seed = SEED_LINE.subn(f"seed: {seed}\n", text, count=1)
    if (n_pin, n_conc, n_seed) != (1, 1, 1):
        raise SystemExit(
            "the arm does not carry the three expected anchors "
            f"(pin={n_pin}, concurrency={n_conc}, seed={n_seed}); "
            "the generator needs updating before it can be trusted"
        )
    return text


def verify(output: str, source: str, seed: int, deal: list[str]) -> None:
    """Re-read what was written and check it says what it was meant to.

    The parsed form is compared against the source arm with exactly the three
    intended edits applied, so an edit that landed somewhere else - or a key
    that was silently dropped or defaulted - fails here rather than in a run
    that has already spent hours of model time.
    """
    got = yaml.safe_load(output)
    want = yaml.safe_load(source)
    want["game"].pop("traitor_names")
    want["seed"] = seed
    want["llm"]["max_concurrency"] = SWEEP_CONCURRENCY
    assert got == want, "generated config differs from its arm beyond the edits"
    assert "traitor_names" not in got["game"], "the pin is still there"
    assert got["seed"] == seed, f"seed is {got['seed']}, expected {seed}"
    assert got["llm"]["max_concurrency"] == SWEEP_CONCURRENCY
    drawn = sorted(
        random.Random(got["seed"]).sample(
            got["game"]["player_names"], got["game"]["traitors"]
        )
    )
    assert drawn == deal, f"the config draws {drawn}, not {deal}"
    assert seed % 10 < 7, "a holdout seed cannot drive a promotion decision"


def main() -> None:
    names = list(sys.argv[1:] or ARMS)
    pinned: list[str] | None = None
    seed = deal = None
    for name in names:
        arm = CONFIGS / f"season_uk_s01.{name}.yaml"
        if not arm.exists():
            raise SystemExit(f"no such arm: {arm.name}")
        source = arm.read_text()
        raw = yaml.safe_load(source)
        game = raw["game"]
        # Every arm has to pin the same trio, or "the season's three" means
        # something different in each file and the sweep is not one deal.
        if pinned is None:
            pinned = game["traitor_names"]
            seed, deal = pick_deal(
                game["player_names"], game["traitors"], pinned
            )
            print(f"deal: seed {seed} draws {', '.join(deal)}")
            print(f"      (keeps none of the pinned {', '.join(pinned)})")
        elif game["traitor_names"] != pinned:
            raise SystemExit(
                f"{arm.name} pins {game['traitor_names']}, not {pinned}"
            )

        out = CONFIGS / f"season_uk_s01.{name}.rand.yaml"
        out.write_text(
            HEADER.format(
                source=arm.name, arm=name, n=len(names),
                arm_conc=raw["llm"]["max_concurrency"],
                naive=raw["llm"]["max_concurrency"] * len(names),
                conc=SWEEP_CONCURRENCY,
                rule=(
                    f"# seed {seed}: the lowest seed whose draw keeps none of\n"
                    f"# the season's three traitors and is not a holdout seed."
                ),
            )
            + render(source, seed, raw["llm"]["max_concurrency"])
        )
        verify(out.read_text(), source, seed, deal)
        changed = [
            line for line in out.read_text().splitlines()
            if line not in source.splitlines()
        ]
        print(f"wrote {out.name}: {len(changed)} lines differ, verified")


if __name__ == "__main__":
    main()
