"""Run the random-deal arm sweep: every arm at once, against one host.

The arms are generated by `make_rand_arms.py`, which drops the season's
`traitor_names` pin so all of them draw the same deal from the seed. What is
left is a set of configs that differ by one flag each, which is what makes the
comparison readable, and this tool exists to start them together.

The arms run in waves, a few at a time. Running all seven together was the
first attempt and it does not work against a host whose parallel capacity is
below that: past what a host serves, the failure here is not slowness but closed
connections - the model never answers, the retries do not absorb it, and the run
ends. "8 in flight is clean" is a property of the host it was measured on, not
of the model, which is the same trap the `fix_hl` header records. A wave keeps
the requests in flight at what the host actually serves.

Wave membership is deliberate, so the tightest comparisons stay inside a wave:
the control and the arms nearest it first, then the arms that stack the later
flags, with a parent and its single-flag child kept together wherever the split
allows. What a wave cannot fix is that an arm in wave 1 and an arm in wave 2
did not run under the same host conditions - which is why the interruptions are
counted per arm and reported next to the results rather than left in the logs.

Every arm runs under a supervisor. A transport failure that exhausts the
provider's retries propagates out of the run and ends it, so for a run this
long one closed socket is the difference between losing a night and losing a
phase. The resume machinery exists for exactly this and nothing invoked it
automatically; the supervisor does, relaunching a crashed arm with `--resume`
so it continues from the last completed phase of its own log. Seven arms are
seven chances for one socket to end the sweep.

Supervision does not make an arm identical to an uninterrupted run: a resume
discards the phase that was cut off, so that phase's calls are paid for again.
Each attempt writes a header into the arm's log, so the number of resumes is
readable afterwards (`grep -c attempt <arm>.log`) rather than inferred from
the tracebacks between them. Two arms resumed a different number of times were
not asked quite the same question, and that belongs next to their numbers.

Nothing here writes an address into the repository. `--base-url` keeps the
endpoint on the command line; the run's own captured config records it inside
its run folder, which is gitignored.

Usage:
  # the split this sweep uses: the control and the arms nearest it, then the
  # arms that stack the later flags
  uv run --no-sync python tools/run_rand_sweep.py --base-url http://HOST:11434 \
      --wave fix_en,noecho,ptr_opt,ptr_req --wave ptr_mem,ledger,ledger_room
  uv run --no-sync python tools/run_rand_sweep.py --base-url ... --dry-run
  # every arm at once, or a single arm
  uv run --no-sync python tools/run_rand_sweep.py --base-url ... --arms ledger
  # continue arms already on disk (a plain run skips a folder that exists)
  uv run --no-sync python tools/run_rand_sweep.py --base-url ... --resume

Watch one while it runs:
  uv run --no-sync python tools/run_health.py runs/uk-s01-rand-ledger

Stop:
  kill <pid>                # a supervisor, from <log-dir>/launch.txt
  pkill -f 'uk-s01-rand-'   # every supervisor and the run under it
"""
from __future__ import annotations

import argparse
import re
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

# One list, owned by the generator, so the sweep cannot drift from the set of
# arms that were actually generated.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_rand_arms import ARMS  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]

# How a crashed arm is recovered. Both numbers exist because the failure that
# triggers a resume is usually gone by the next attempt, while a host that is
# down fails every attempt within seconds: without a pause and a cap, the
# supervisor would spend the night failing at it.
DEFAULT_MAX_RESUMES = 20
DEFAULT_RESUME_BACKOFF = 60.0

# `load_point` refuses to rewrite a log that moved recently, on the grounds
# that a live run is holding it. A crash lands inside that window, so the
# resume is told the log is idle after five seconds instead: the directory
# lock, not the clock, is what proves the writer is gone.
RESUME_IDLE_SECONDS = 5

# What is in flight, so a SIGTERM takes the runs with the process watching
# them instead of leaving them behind with nobody to report on them. A
# supervisor holds one attempt; a wave runner holds one supervisor per arm in
# the wave it is waiting on.
_child: Optional[subprocess.Popen] = None
_children: list[subprocess.Popen] = []


def command_for_attempt(
    attempt: int, *, fresh: list[str], resume: list[str], resume_first: bool
) -> list[str]:
    """The command for one attempt at one arm.

    Attempt 1 is a new run, unless the caller asked to continue a folder that
    is already on disk, in which case it is a resume. Every later attempt is a
    resume: by then the folder exists and its event log is the only account of
    the rounds that already happened.
    """
    if attempt > 1 or resume_first:
        return resume
    return fresh


def should_retry(exit_code: int, attempt: int, max_resumes: int) -> bool:
    """Whether an attempt that just returned leaves something to continue.

    Zero means the game finished, and there is nothing to resume. Anything
    else is a crash - a transport failure, most often - and the run folder is
    still there with a playable history in it, so the next attempt continues
    it. The cap is on resumes, not attempts: the first run is not one.
    """
    return exit_code != 0 and attempt <= max_resumes


# The header a supervisor writes before each attempt. Counting these is how an
# arm's interruptions get reported, and the pattern lives here, next to the
# writer, because a counter that drifts from the format it reads is a count
# nobody should trust.
ATTEMPT_HEADER = re.compile(
    r"^--- \S+ attempt \d+ \((?:new run|resume)\)", re.M
)


def attempts_so_far(log: Path) -> int:
    """How many times an arm has been started, read from its own log.

    This is the number that belongs next to an arm's results: a resume throws
    away the phase it interrupted and replays it, so an arm interrupted more
    often than its neighbour was not asked quite the same question.
    """
    if not log.exists():
        return 0
    return len(ATTEMPT_HEADER.findall(log.read_text(encoding="utf-8")))


def parse_wave(text: str) -> list[str]:
    """One `--wave` value: arm names, separated by commas or spaces.

    Checked against the generated set here rather than left to be discovered:
    an arm nobody generated would otherwise be found by a supervisor that
    exits at once, hours into an unattended sweep.
    """
    arms = [arm for arm in re.split(r"[,\s]+", text.strip()) if arm]
    if not arms:
        raise SystemExit(f"empty wave: {text!r}")
    unknown = [arm for arm in arms if arm not in ARMS]
    if unknown:
        raise SystemExit(
            f"unknown arm(s) {', '.join(unknown)} in wave {text!r}; "
            f"the generated set is {' '.join(ARMS)}"
        )
    return arms


def _commands(arm: str, game_id: str, base_url: str) -> tuple[list[str], list[str]]:
    """The new-run command and the resume command for one arm.

    The config is checked here rather than assumed: an arm nobody generated
    would otherwise start a run that fails on its first model call, hours
    after the sweep was left to itself.
    """
    config = ROOT / "configs" / "traitors" / f"season_uk_s01.{arm}.rand.yaml"
    if not config.exists():
        raise SystemExit(
            f"no {config.name}; run tools/make_rand_arms.py {arm} first"
        )
    fresh = [
        # -u because stdout is a file here: buffered, the log stays empty for
        # the whole run and a traceback is lost with the buffer.
        sys.executable, "-u", "-m", "simulation", "run", str(config),
        "--game-id", game_id, "--base-url", base_url, "--quiet",
    ]
    return fresh, fresh + ["--resume", "--idle-seconds", str(RESUME_IDLE_SECONDS)]


def _pretty(command: list[str]) -> str:
    """A command as the reader would type it: repo-relative, uv in front."""
    parts = [str(part).replace(str(ROOT) + "/", "") for part in command[1:]]
    return "uv run --no-sync python " + " ".join(parts)


def _supervisor_command(
    arm: str, game_id: str, args: argparse.Namespace, *, resume_first: bool
) -> list[str]:
    """The command that supervises one arm, in its own session.

    `--session-name` puts the run id into the supervisor's command line as
    well as the run's. That is what keeps the documented
    `pkill -f 'uk-s01-rand-'` honest: a supervisor that outlived its own run
    would only resume it, undoing the kill.
    """
    command = [
        sys.executable, "-u", str(Path(__file__).resolve()),
        "--base-url", args.base_url,
        "--supervise", "--arms", arm, "--session-name", game_id,
        "--runs-dir", args.runs_dir, "--log-dir", args.log_dir,
        "--max-resumes", str(args.max_resumes),
        "--resume-backoff", str(args.resume_backoff),
    ]
    if resume_first:
        command.append("--resume")
    return command


def _terminate_children(signum: int, _frame: object) -> None:  # pragma: no cover
    """Take what is in flight with the process watching it, then stop."""
    for child in [_child, *_children]:
        if child is not None and child.poll() is None:
            child.terminate()
    raise SystemExit(128 + signum)


def supervise(args: argparse.Namespace) -> int:
    """Run one arm to the end, resuming it after a crash.

    Foreground, and the return value is the last attempt's exit code. One
    header per attempt goes into the arm's log, appended rather than
    truncated, so a log that already holds a crash keeps it: how the arm died
    is evidence too, and the headers around it say how many times that
    happened.
    """
    global _child
    if len(args.arms) != 1:
        raise SystemExit("--supervise takes exactly one arm")
    arm = args.arms[0]
    game_id = args.session_name or f"uk-s01-rand-{arm}"
    fresh, resume = _commands(arm, game_id, args.base_url)
    log = ROOT / args.log_dir / f"{arm}.log"
    log.parent.mkdir(parents=True, exist_ok=True)
    signal.signal(signal.SIGTERM, _terminate_children)

    attempt = 1
    with log.open("a", encoding="utf-8") as handle:
        while True:
            resuming = attempt > 1 or args.resume
            command = command_for_attempt(
                attempt, fresh=fresh, resume=resume, resume_first=args.resume
            )
            handle.write(
                f"\n--- {game_id} attempt {attempt} "
                f"({'resume' if resuming else 'new run'}) "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')} ---\n"
            )
            handle.flush()
            _child = subprocess.Popen(
                command, cwd=ROOT, stdout=handle, stderr=subprocess.STDOUT
            )
            exit_code = _child.wait()
            _child = None
            if not should_retry(exit_code, attempt, args.max_resumes):
                handle.write(
                    f"--- {game_id} stopped: exit {exit_code} after "
                    f"{attempt} attempt(s) ---\n"
                )
                return exit_code
            handle.write(
                f"--- {game_id} exited {exit_code}; resuming in "
                f"{args.resume_backoff:.0f}s ---\n"
            )
            handle.flush()
            time.sleep(args.resume_backoff)
            attempt += 1

def _orchestrator_command(args: argparse.Namespace) -> list[str]:
    """The command that runs the waves, in its own session.

    Detached like the supervisors, so the waves outlive the shell that started
    them: a wave runner has to stay alive for the length of the sweep, since
    its whole job is waiting for one wave before starting the next.
    """
    command = [
        sys.executable, "-u", str(Path(__file__).resolve()),
        "--base-url", args.base_url,
        "--orchestrate", "--session-name", "uk-s01-rand-sweep",
        "--runs-dir", args.runs_dir, "--log-dir", args.log_dir,
        "--max-resumes", str(args.max_resumes),
        "--resume-backoff", str(args.resume_backoff),
    ]
    for wave in args.wave:
        command += ["--wave", wave]
    return command


def orchestrate(args: argparse.Namespace) -> int:
    """Run the arms in waves, one wave at a time, in the foreground.

    A wave is started, waited for, and only then is the next one started: the
    point of the waves is the ceiling on requests in flight, and launching the
    next one early would put the sweep back where it started. Each wave's
    supervisors and runs are logged into `waves.log`; the arm logs keep their
    own attempt headers, which is where the per-arm interruption count is read.
    """
    global _children
    waves = [parse_wave(text) for text in args.wave]
    runs_dir = ROOT / args.runs_dir
    log = ROOT / args.log_dir / "waves.log"
    log.parent.mkdir(parents=True, exist_ok=True)
    signal.signal(signal.SIGTERM, _terminate_children)

    worst = 0
    with log.open("a", encoding="utf-8") as handle:
        for index, wave in enumerate(waves, start=1):
            handle.write(
                f"\n=== wave {index}/{len(waves)} "
                f"{time.strftime('%Y-%m-%d %H:%M:%S')}: {' '.join(wave)} ===\n"
            )
            handle.flush()
            _children = []
            for arm in wave:
                game_id = f"uk-s01-rand-{arm}"
                # An arm already on disk is resumed: a wave is a sweep being
                # continued, and the rounds in its log cannot be replayed away.
                command = _supervisor_command(
                    arm, game_id, args,
                    resume_first=(runs_dir / game_id).exists(),
                )
                _children.append(
                    subprocess.Popen(
                        command, cwd=ROOT, stdout=handle,
                        stderr=subprocess.STDOUT,
                        start_new_session=True,
                    )
                )
            codes = [child.wait() for child in _children]
            _children = []
            for arm, code in zip(wave, codes):
                attempts = attempts_so_far(ROOT / args.log_dir / f"{arm}.log")
                handle.write(
                    f"wave {index}: {arm} exit {code}, {attempts} attempt(s)\n"
                )
                worst = max(worst, code)
            handle.flush()
        handle.write(
            f"\n=== sweep finished {time.strftime('%Y-%m-%d %H:%M:%S')} "
            f"({len(waves)} wave(s)) ===\n"
        )
    return 1 if worst else 0


def launch_waves(args: argparse.Namespace) -> None:
    """Start the wave runner, detached, and record what was started."""
    _refuse_open_bugs()
    log = ROOT / args.log_dir / "waves.log"
    log.parent.mkdir(parents=True, exist_ok=True)
    command = _orchestrator_command(args)
    if args.dry_run:
        print(f"would start: {_pretty(command)}")
        for index, text in enumerate(args.wave, start=1):
            print(f"             wave {index}: {' '.join(parse_wave(text))}")
        print(f"             logs -> {args.log_dir}/waves.log and "
              f"{args.log_dir}/<arm>.log")
        return

    with log.open("ab") as handle:
        process = subprocess.Popen(
            command, cwd=ROOT, stdout=handle,
            stderr=subprocess.STDOUT, start_new_session=True,
        )
    wave_lines = [
        f"wave {index}: {' '.join(parse_wave(text))}\n"
        for index, text in enumerate(args.wave, start=1)
    ]
    (ROOT / args.log_dir / "launch.txt").write_text(
        f"started a supervised sweep in {len(args.wave)} wave(s) "
        f"against the host given\n"
        f"one wave at a time: wave 1 runs now, the next starts when this one "
        f"finishes, so the\nrequests in flight stay at what the host serves\n"
        f"each arm is resumed from its own log after a crash; the attempt "
        f"headers in\n<arm>.log count an arm's interruptions, and waves.log "
        f"reports them per wave\n"
        f"stop one arm:  pkill -f 'uk-s01-rand-<arm>'\n"
        f"stop all:      pkill -f 'uk-s01-rand-'   "
        f"(wave runner, supervisors and runs)\n"
        f"wave runner:   pid {process.pid}\n\n"
        + "\n".join(wave_lines)
    )
    print(f"\nstarted the sweep in {len(args.wave)} wave(s) "
          f"against the host given")
    print(f"wave runner pid {process.pid}; logs: {args.log_dir}/waves.log and "
          f"{args.log_dir}/<arm>.log")
    print("\nOne wave at a time, in the order given, so the requests in flight "
          "stay at what\nthe host serves. Watch the running wave with\n"
          "  uv run --no-sync python tools/run_health.py "
          f"{args.runs_dir}/uk-s01-rand-{parse_wave(args.wave[0])[0]}\n"
          "and read a stall as queueing into the timeout, not as emptiness. A "
          "crash costs\nan arm one phase, not the run: the supervisor resumes "
          "it.")


def _refuse_open_bugs() -> None:
    """Refuse to start anything over a known blocking bug.

    A run started over one corrupts its own data, and the corruption surfaces
    later, indistinguishable from a finding. The run itself refuses too;
    failing here catches it for the whole sweep at once rather than leaving
    seven logs saying the same thing.
    """
    gate = subprocess.run(
        [sys.executable, str(ROOT / "tools" / "bug_gate.py"), "--quiet"],
        cwd=ROOT,
    )
    if gate.returncode != 0:
        raise SystemExit(
            "a blocking bug is open in docs/todo.md; not starting the sweep"
        )


def launch(args: argparse.Namespace) -> None:
    """Start one supervisor per arm, and record what was started."""
    _refuse_open_bugs()

    log_dir = ROOT / args.log_dir
    runs_dir = ROOT / args.runs_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    started: list[tuple[str, str, int]] = []

    for arm in args.arms:
        game_id = f"uk-s01-rand-{arm}"
        fresh, resume = _commands(arm, game_id, args.base_url)
        exists = (runs_dir / game_id).exists()
        if exists and not args.resume:
            # Two writers on one game id would corrupt the log, and the rounds
            # already in it cannot be replayed away. Continuing a dead run is
            # a decision to make on purpose.
            print(f"skip {game_id}: the run folder exists "
                  f"(continue it with --resume, or move it aside)")
            continue
        command = _supervisor_command(arm, game_id, args, resume_first=exists)
        if args.dry_run:
            print(f"would start: {_pretty(command)}")
            print(f"             first attempt: "
                  f"{_pretty(resume if exists else fresh)}")
            print(f"             log -> {args.log_dir}/{arm}.log")
            continue

        log = log_dir / f"{arm}.log"
        with log.open("ab") as handle:
            process = subprocess.Popen(
                command, cwd=ROOT, stdout=handle,
                stderr=subprocess.STDOUT,
                # Its own session, so the sweep keeps running after the shell
                # that started it goes away.
                start_new_session=True,
            )
        started.append((arm, game_id, process.pid))

    if args.dry_run or not started:
        return

    # Written down because a sweep runs for hours and the person who has to
    # stop it is not always the person who started it.
    lines = [
        f"pid {pid}  {game_id}\n    {ROOT}/configs/traitors/"
        f"season_uk_s01.{arm}.rand.yaml\n"
        for arm, game_id, pid in started
    ]
    (log_dir / "launch.txt").write_text(
        f"started {len(started)} supervised run(s) against the host given\n"
        f"a crashed arm is resumed from its own log, up to "
        f"{args.max_resumes} resumes; every attempt\nwrites a header into "
        f"<arm>.log, and that count is how often an arm was broken into\n"
        f"stop one:  kill <pid>      (the run under it goes too)\n"
        f"stop all:  pkill -f 'uk-s01-rand-'\n\n"
        + "\n".join(lines)
    )

    print(f"\nstarted {len(started)} supervised run(s) against the host given")
    print(f"logs: {args.log_dir}/<arm>.log   pids: {args.log_dir}/launch.txt")
    print("\nThe host serves a fixed number of requests in parallel, so the "
          "first rounds\nare the slowest: every arm is warming up at once. "
          "Check one with\n  uv run --no-sync python tools/run_health.py "
          f"{args.runs_dir}/uk-s01-rand-{started[0][0]}\n"
          "and read a stall as queueing into the timeout, not as emptiness. "
          "A crash costs\nan arm one phase, not the run: the supervisor "
          "resumes it, and the attempt\nheaders in the log say how often "
          "that had to happen.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base-url", required=True,
                    help="the host that serves the model, e.g. http://HOST:11434")
    ap.add_argument("--arms", nargs="*", default=list(ARMS),
                    help=f"arms to run, all at once (default: {' '.join(ARMS)}); "
                         "ignored when --wave is given")
    ap.add_argument("--wave", action="append", default=[], metavar="ARM,ARM",
                    help="arms to run together, as one wave: repeat the flag "
                         "for more waves, and each wave starts when the one "
                         "before it finishes. Use it on a host that does not "
                         "serve the whole set at once, e.g. --wave "
                         "fix_en,noecho,ptr_opt,ptr_req --wave "
                         "ptr_mem,ledger,ledger_room")
    ap.add_argument("--runs-dir", default="runs")
    ap.add_argument("--log-dir", default="runs/_rand-sweep",
                    help="where each arm's output is written (gitignored)")
    ap.add_argument("--resume", action="store_true",
                    help="continue the run folders that already exist, instead "
                         "of skipping them: an arm already on disk resumes first")
    ap.add_argument("--max-resumes", type=int, default=DEFAULT_MAX_RESUMES,
                    help="how many times one arm may be resumed after a crash "
                         f"(default {DEFAULT_MAX_RESUMES})")
    ap.add_argument("--resume-backoff", type=float, default=DEFAULT_RESUME_BACKOFF,
                    help="seconds between a crash and the attempt that resumes "
                         f"it (default {DEFAULT_RESUME_BACKOFF:.0f})")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the commands instead of starting anything")
    ap.add_argument("--supervise", action="store_true",
                    help="internal: watch one arm in the foreground and resume "
                         "it after a crash, instead of returning")
    ap.add_argument("--orchestrate", action="store_true",
                    help="internal: run the waves in the foreground, waiting "
                         "for each wave before starting the next")
    ap.add_argument("--session-name", default="",
                    help="internal: the run id being supervised, kept in this "
                         "process's command line so `pkill -f 'uk-s01-rand-'` "
                         "reaches it")
    args = ap.parse_args()

    if args.supervise:
        raise SystemExit(supervise(args))
    if args.orchestrate:
        raise SystemExit(orchestrate(args))
    if args.wave:
        launch_waves(args)
        return
    launch(args)


if __name__ == "__main__":
    main()
