"""Run the random-deal arm sweep: every arm at once, against one host.

The arms are generated by `make_rand_arms.py`, which drops the season's
`traitor_names` pin so all of them draw the same deal from the seed. What is
left is a set of configs that differ by one flag each, which is what makes the
comparison readable, and this tool exists to start them together.

Sequential would be simpler and is worse in three ways. A queue means the last
arm runs when the host is least healthy, so the arms are not compared under
like conditions. The host serves a fixed number of requests in parallel and
these configs record 8 in flight as clean and 16 as degraded, so the arms have
to share that budget rather than each claiming the tracked four. And a sweep
left to one-at-a-time finishes over several days, which is long enough that
the model tag on the host is no longer the same experiment.

Nothing here writes an address into the repository. `--base-url` keeps the
endpoint on the command line; the run's own captured config records it inside
its run folder, which is gitignored.

Usage:
  uv run --no-sync python tools/run_rand_sweep.py --base-url http://HOST:11434
  uv run --no-sync python tools/run_rand_sweep.py --base-url ... --dry-run
  uv run --no-sync python tools/run_rand_sweep.py --base-url ... --arms ledger

Watch one while it runs:
  uv run --no-sync python tools/run_health.py runs/uk-s01-rand-ledger
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

# One list, owned by the generator, so the sweep cannot drift from the set of
# arms that were actually generated.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from make_rand_arms import ARMS  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base-url", required=True,
                    help="the host that serves the model, e.g. http://HOST:11434")
    ap.add_argument("--arms", nargs="*", default=list(ARMS),
                    help=f"arms to run (default: {' '.join(ARMS)})")
    ap.add_argument("--runs-dir", default="runs")
    ap.add_argument("--log-dir", default="runs/_rand-sweep",
                    help="where each arm's output is written (gitignored)")
    ap.add_argument("--dry-run", action="store_true",
                    help="print the commands instead of starting anything")
    args = ap.parse_args()

    # A run started over a known blocking bug corrupts its own data, and the
    # corruption surfaces later, indistinguishable from a finding. The run
    # itself refuses too; failing here catches it for the whole sweep at once
    # rather than leaving seven logs saying the same thing.
    gate = subprocess.run(
        [sys.executable, str(ROOT / "tools" / "bug_gate.py"), "--quiet"],
        cwd=ROOT,
    )
    if gate.returncode != 0:
        raise SystemExit(
            "a blocking bug is open in docs/todo.md; not starting the sweep"
        )

    log_dir = ROOT / args.log_dir
    runs_dir = ROOT / args.runs_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    launched: list[tuple[str, str, int, Path]] = []

    for arm in args.arms:
        config = ROOT / "configs" / "traitors" / f"season_uk_s01.{arm}.rand.yaml"
        if not config.exists():
            raise SystemExit(
                f"no {config.name}; run tools/make_rand_arms.py {arm} first"
            )
        game_id = f"uk-s01-rand-{arm}"
        command = [
            # -u because stdout is a file here: buffered, the log stays empty
            # for the whole run and a traceback is lost with the buffer.
            sys.executable, "-u", "-m", "simulation", "run", str(config),
            "--game-id", game_id, "--base-url", args.base_url, "--quiet",
        ]
        pretty = "uv run --no-sync python " + " ".join(
            str(part).replace(str(ROOT) + "/", "") for part in command[1:]
        )
        if (runs_dir / game_id).exists():
            # Two writers on one game id would corrupt the log, and the
            # rounds already in it cannot be replayed away. A dead run is
            # continued with --resume, which is a decision to make on purpose.
            print(f"skip {game_id}: the run folder exists "
                  f"(resume it, or move it aside)")
            continue
        if args.dry_run:
            print(f"would start: {pretty}")
            print(f"             log -> {args.log_dir}/{arm}.log")
            continue

        log = log_dir / f"{arm}.log"
        with log.open("wb") as handle:
            process = subprocess.Popen(
                command, cwd=ROOT, stdout=handle,
                stderr=subprocess.STDOUT,
                # Its own session, so the sweep keeps running after the shell
                # that started it goes away.
                start_new_session=True,
            )
        launched.append((arm, game_id, process.pid, log))

    if args.dry_run or not launched:
        return

    # Written down because a sweep runs for hours and the person who has to
    # stop it is not always the person who started it.
    lines = [
        f"pid {pid}  {game_id}\n    {ROOT}/configs/traitors/"
        f"season_uk_s01.{arm}.rand.yaml\n"
        for arm, game_id, pid, _ in launched
    ]
    (log_dir / "launch.txt").write_text(
        f"started {len(launched)} run(s) against {args.base_url}\n"
        f"stop one:  kill <pid>\nstop all:  pkill -f 'uk-s01-rand-'\n\n"
        + "\n".join(lines)
    )

    print(f"\nstarted {len(launched)} run(s) against the host given")
    print(f"logs: {args.log_dir}/<arm>.log   pids: {args.log_dir}/launch.txt")
    print("\nThe host serves a fixed number of requests in parallel, so the "
          "first rounds\nare the slowest: every arm is warming up at once. "
          "Check one with\n  uv run --no-sync python tools/run_health.py "
          f"{args.runs_dir}/uk-s01-rand-{launched[0][0]}\n"
          "and read a stall as queueing into the timeout, not as emptiness.")


if __name__ == "__main__":
    main()
